package info.openrocket.core.aerodynamics.physicsaero.separation;
public enum SeparationState { ATTACHED, ADVERSE_GRADIENT_WARNING, INCIPIENT_SEPARATION, PROBABLE_SEPARATION, SEPARATED, REATTACHMENT_CANDIDATE, REATTACHED_LOW_CONFIDENCE, INVALID }
