package info.openrocket.core.aerodynamics.physicsaero.runtime;

/** Stable flags emitted by the experimental table runtime and reports. */
public enum PhysicsAeroRuntimeFlag {
	FLIGHT_VALIDATION_PENDING,
	SINGLE_STAGE_ONLY,
	TABLE_QUERY_USED,
	RUNTIME_REYNOLDS_CORRECTION_USED,
	LOW_DENSITY_REYNOLDS_SOURCE_BOUNDARY_HOLD,
	LOW_CONFIDENCE_CELL_USED,
	DIAGNOSTIC_FALLBACK_USED,
	AXIAL_ONLY_HYBRID_USED,
	AXIAL_INCIDENCE_SYMMETRY_PROJECTION,
	INCIDENCE_AZIMUTH_RECONSTRUCTION,
	LAUNCH_GUIDE_AXIAL_TABLE_PROJECTION,
	POWERED_STATE_FALLBACK,
	POWERED_INCREMENT_UNMODELED,
	OUT_OF_DOMAIN,
	INTERPOLATION_EVENT_BOUNDARY,
	REYNOLDS_REBUILD_REQUIRED,
	RATE_DERIVATIVES_ENGINEERING_ONLY
}
