package info.openrocket.core.aerodynamics.physicsaero.api;

public enum PhysicalTerm {
	BODY_PRESSURE, BODY_PRESSURE_FOREBODY, BODY_PRESSURE_TRANSITION, FIN_PRESSURE, BODY_NORMAL_POTENTIAL, BODY_VISCOUS_CROSSFLOW,
	FIN_LIFT, FIN_ZERO_LIFT_WAVE_DRAG, FIN_LIFT_DEPENDENT_DRAG, SKIN_FRICTION,
	BASE_PRESSURE_DRAG, BOATTAIL_PRESSURE_DRAG, SEPARATION_DRAG, INTERFERENCE_FORCE,
	INTERFERENCE_DRAG, BODY_UPWASH_NORMAL_FORCE, BODY_FIN_INTERFERENCE_NORMAL_FORCE, BODY_FIN_INTERFERENCE_MOMENT,
	BODY_FIN_INTERFERENCE_DRAG, SHOCK_IMPINGEMENT_PRESSURE, SHOCK_PRESSURE, SWBLI_PRESSURE_RECOVERY, PLUME_CORRECTION
}
