package info.openrocket.core.aerodynamics.physicsaero;

import static org.junit.jupiter.api.Assertions.*;
import java.time.Instant;
import java.util.*;
import org.junit.jupiter.api.Test;
import info.openrocket.core.aerodynamics.physicsaero.blending.*;
import info.openrocket.core.aerodynamics.physicsaero.flow.*;
import info.openrocket.core.aerodynamics.physicsaero.force.AerodynamicCoefficients;
import info.openrocket.core.aerodynamics.physicsaero.gasdynamics.*;
import info.openrocket.core.aerodynamics.physicsaero.geometry.*;
import info.openrocket.core.aerodynamics.physicsaero.integration.*;
import info.openrocket.core.aerodynamics.physicsaero.runtime.*;
import info.openrocket.core.aerodynamics.physicsaero.subsonic.*;
import info.openrocket.core.aerodynamics.physicsaero.table.*;
import info.openrocket.core.aerodynamics.physicsaero.thermodynamics.*;
import info.openrocket.core.aerodynamics.physicsaero.transonic.*;
import info.openrocket.core.util.Coordinate;

class PhaseSixFullRegimeTest {
	@Test void lowSpeedSelectorHasContinuousMachPointThreeOverlap(){LowSpeedRegimeSelector s=new LowSpeedRegimeSelector();assertEquals(0,s.correlationWeight(.25),1e-15);assertEquals(1,s.correlationWeight(.35),1e-15);assertEquals(.5,s.correlationWeight(.3),1e-12);assertEquals(LowSpeedRegimeSelector.Regime.BARROWMAN_CORRELATION_OVERLAP,s.select(.3));}
	@Test void karmanTsienRecoversLowMachAndNeverEvaluatesAtSonic(){KarmanTsienCorrection k=new KarmanTsienCorrection();assertEquals(-.2,k.apply(-.2,0).pressureCoefficient(),1e-15);assertTrue(k.apply(-.2,.7).pressureCoefficient()<-.2);assertFalse(k.apply(-.2,1).valid());}
	@Test void cylinderSourceDistributionHasZeroPerturbation(){List<GeometryStation>s=List.of(new GeometryStation(0,.1,0,0),new GeometryStation(1,.1,0,0));var v=new AxisymmetricSourceDistribution().velocityAt(s,0,100);assertEquals(0,v.axialMS(),1e-15);assertEquals(0,v.radialMS(),1e-15);}
	@Test void subsonicDatcomIsFiniteAndCompressibilityRaisesSlope(){SubsonicDatcomFinModel d=new SubsonicDatcomFinModel();double low=d.liftSlopePerRad(0,2,0,1),high=d.liftSlopePerRad(.8,2,0,1);assertTrue(low>0);assertTrue(high>low);assertThrows(IllegalArgumentException.class,()->d.liftSlopePerRad(1,2,0,1));}
	@Test void criticalMachAndDragDivergenceRemainDistinct(){double cr=new FinCriticalMachEstimator().estimate(.05,0,0).criticalMach();double dd=new FinDragDivergenceEstimator().estimate(.05,0,0,.92).dragDivergenceMach();assertNotEquals(cr,dd);assertTrue(dd>cr);}
	@Test void embeddedShockRequiresPhysicalLocalSupersonicState(){PerfectGasAir air=new PerfectGasAir();SurfaceState sub=surface(.9,air);assertThrows(IllegalArgumentException.class,()->new EmbeddedShockModel().terminatePocket(.5,sub,air));SurfaceState sup=surface(1.1,air);assertTrue(new EmbeddedShockModel().terminatePocket(.5,sup,air).downstream().staticState().mach()<1);}
	@Test void dedicatedTransonicPeakHasGrowthPeakAndRecovery(){var p=new TransonicDragRiseModel.Parameters(.8,.9,1.02,.2,1.4,2,4,"test");TransonicDragRiseModel m=new TransonicDragRiseModel();assertEquals(0,m.deltaCd(.8,0,p),0);assertTrue(m.deltaCd(.95,1,p)<m.deltaCd(1.02,1,p));assertEquals(.2,m.deltaCd(1.02,1,p),1e-15);assertTrue(m.deltaCd(1.3,1,p)<.2);}
	@Test void reliabilityBlendingAndContinuityAreBounded(){AerodynamicCoefficients a=new AerodynamicCoefficients(.1,1,0,0,0,0),b=new AerodynamicCoefficients(.2,2,0,0,0,0);var c=new ComponentRegimeBlender().blend(a,3,b,1);assertEquals(.125,c.ca(),1e-15);var result=new BlendContinuityValidator().validate(new double[]{.8,.9,1},new double[]{.1,.11,.12},.02,.2);assertTrue(result.valid());}
	@Test void runtimeReynoldsCorrectionRejectsTopologyChange(){var base=new AerodynamicCoefficients(.2,1,0,0,0,0);var surface=new ReynoldsSensitivitySurface(1e6,.5,2,new double[]{-.02,0,0,0,0,0},"friction",true);assertTrue(new RuntimeAtmosphereCorrection().apply(base,1.5e6,surface,false).valid());assertFalse(new RuntimeAtmosphereCorrection().apply(base,1.5e6,surface,true).valid());}
	@Test void thermallyPerfectAirAndVariablePropertySolversConserveInvariants(){ThermallyPerfectAir air=new ThermallyPerfectAir();assertTrue(air.gamma(1500)<air.gamma(300));assertTrue(air.totalTemperature(300,1000)>300);double p=101325,t=300,rho=p/(air.gasConstant()*t),u=3*air.speedOfSound(t);var shock=new VariablePropertyShockSolver().normalShock(p,t,rho,u,air);assertTrue(shock.converged());assertTrue(shock.downstreamVelocityMS()<u);var expansion=new VariablePropertyExpansionSolver().expand(shock.downstreamPressurePa(),shock.downstreamTemperatureK(),shock.downstreamVelocityMS(),p,air);assertTrue(expansion.converged());}
	@Test void equilibriumAirPreservesElementsAndHighMachHandoffIsExplicit(){var eq=new EquilibriumAirModel().equilibrium(4000,101325);assertTrue(eq.converged());assertEquals(0,eq.nitrogenResidual(),1e-10);assertEquals(0,eq.oxygenResidual(),1e-10);PerfectGasAir gas=new PerfectGasAir();double v=6*gas.speedOfSound(288.15);assertNotEquals(HighMachThermodynamicSelector.Model.PERFECT_GAS,new HighMachThermodynamicSelector().select(6,288.15,v).model());}
	@Test void fullMachZeroToSevenTableIsFiniteDeterministicAndLegacyFree(){AeroGeometry geometry=geometry();PerfectGasAir air=new PerfectGasAir();double p=101325,t=288.15;AtmosphereState atmosphere=new AtmosphereState(p,t,p/(air.gasConstant()*t),air.viscosity(t));double[]m={0,.3,.8,.95,1.05,1.2,2,5,6,7},a={Math.toRadians(-5),0,Math.toRadians(5)},b={0};TableMetadata md=new TableMetadata(TableMetadata.CURRENT_SCHEMA,geometry.geometryHash(),"phase6","test","v1","SI;radians","OPENROCKET_BODY_AXES_V1",Instant.parse("2026-01-01T00:00:00Z"),Map.of(),Map.of(),"TEST");AerodynamicTable one=new FullRegimeTableBuilder().build(geometry,m,a,b,atmosphere,air,md),two=new FullRegimeTableBuilder().build(geometry,m,a,b,atmosphere,air,md);assertEquals(30,one.cells().size());for(int i=0;i<one.cells().size();i++){assertArrayEquals(one.cells().get(i).coefficients().toArray(),two.cells().get(i).coefficients().toArray());assertArrayEquals(one.cells().get(i).confidence(),two.cells().get(i).confidence());assertEquals(one.cells().get(i).methodIds(),two.cells().get(i).methodIds());}assertTrue(one.cells().stream().allMatch(c->Arrays.stream(c.coefficients().toArray()).allMatch(Double::isFinite)));one.cells().forEach(c->new LegacyRomRemovalGuard().verify(c));}
	@Test void validationGateAndStaleTablePolicyAreExplicit(){assertEquals(PhysicsAeroValidationGate.Status.PASS,new PhysicsAeroValidationGate().evaluate().status());PhysicsAeroFeatureController c=new PhysicsAeroFeatureController();c.setEnabled(true);assertEquals("MISSING_TABLE_NO_SILENT_FALLBACK",c.staleReason("g","s"));}
	// Regression for the DETACHED_COMPRESSION_CORNER build failure: a body shoulder whose turn exceeds the attached-shock
	// limit at low supersonic Mach (~16 deg shoulder detaches at Mach 1.2, where the maximum deflection is only ~3.6 deg).
	// The supersonic table build (which runs before any subsonic cell) must complete via the explicit modified-Newtonian
	// fallback instead of aborting. The Mach grid stays clear of the unrelated high-subsonic Karman-Tsien validity limit.
	@Test void supersonicShoulderDetachmentFallsBackInsteadOfAbortingBuild(){AeroGeometry geometry=steppedGeometry();PerfectGasAir air=new PerfectGasAir();double p=101325,t=288.15;AtmosphereState atmosphere=new AtmosphereState(p,t,p/(air.gasConstant()*t),air.viscosity(t));double[]m={0,.3,1.2,2,5},a={Math.toRadians(-5),0,Math.toRadians(5)},b={0};TableMetadata md=new TableMetadata(TableMetadata.CURRENT_SCHEMA,geometry.geometryHash(),"phase6","test","v1","SI;radians","OPENROCKET_BODY_AXES_V1",Instant.parse("2026-01-01T00:00:00Z"),Map.of(),Map.of(),"TEST");AerodynamicTable one=assertDoesNotThrow(()->new FullRegimeTableBuilder().build(geometry,m,a,b,atmosphere,air,md)),two=new FullRegimeTableBuilder().build(geometry,m,a,b,atmosphere,air,md);assertEquals(15,one.cells().size());for(int i=0;i<one.cells().size();i++)assertArrayEquals(one.cells().get(i).coefficients().toArray(),two.cells().get(i).coefficients().toArray());assertTrue(one.cells().stream().allMatch(c->Arrays.stream(c.coefficients().toArray()).allMatch(Double::isFinite)));}
	private static AeroGeometry steppedGeometry(){double r0=.1,r1=.115,s=.1;AxisymmetricProfile coneP=new AxisymmetricProfile(List.of(new GeometryStation(0,0,s,0),new GeometryStation(1,r0,s,0)),List.of(),"TEST",1e-9),tubeP=new AxisymmetricProfile(List.of(new GeometryStation(1,r0,0,0),new GeometryStation(2,r0,0,0)),List.of(),"TEST",1e-9);double slope=(r1-r0)/.05;AxisymmetricProfile shoulderP=new AxisymmetricProfile(List.of(new GeometryStation(2,r0,slope,0),new GeometryStation(2.05,r1,slope,0)),List.of(),"TEST",1e-9),aftP=new AxisymmetricProfile(List.of(new GeometryStation(2.05,r1,0,0),new GeometryStation(3,r1,0,0)),List.of(),"TEST",1e-9);AeroComponent cone=component("cone","NOSE_CONICAL",0,1,0,r0,coneP),tube=component("tube","CYLINDER",1,2,r0,r0,tubeP),shoulder=component("shoulder","TRANSITION",2,2.05,r0,r1,shoulderP),aft=component("aft","CYLINDER",2.05,3,r1,r1,aftP);return new AeroGeometry(List.of(cone,tube,shoulder,aft),new ReferenceGeometry(Math.PI*r1*r1,Math.PI*r1*r1,3,2*r1,Map.of(),new Coordinate(),2*r1),"phase6-stepped-body");}
	private static SurfaceState surface(double mach,PerfectGasAir air){double t=288.15,p=101325,a=air.speedOfSound(t),rho=p/(air.gasConstant()*t);GasState s=new GasState(mach,p,t,rho,mach*a);return SurfaceState.of(.5,.1,s,IsentropicRelations.totalState(s,air),0,0,air,"test");}
	private static AeroGeometry geometry(){double r=.1,s=.1;AxisymmetricProfile coneP=new AxisymmetricProfile(List.of(new GeometryStation(0,0,s,0),new GeometryStation(1,r,s,0)),List.of(),"TEST",1e-9),tubeP=new AxisymmetricProfile(List.of(new GeometryStation(1,r,0,0),new GeometryStation(2,r,0,0)),List.of(),"TEST",1e-9);AeroComponent cone=component("cone","NOSE_CONICAL",0,1,0,r,coneP),tube=component("tube","CYLINDER",1,2,r,r,tubeP);return new AeroGeometry(List.of(cone,tube),new ReferenceGeometry(Math.PI*r*r,Math.PI*r*r,2,2*r,Map.of(),new Coordinate(),2*r),"phase6-body");}
	private static AeroComponent component(String id,String classification,double x0,double x1,double r0,double r1,AxisymmetricProfile profile){return new AeroComponent(id,"/"+id,"test",classification,"stage",0,new Coordinate(x0,0,0),x0,x1,Math.max(r0,r1),profile.wettedAreaM2(),2*Math.max(r0,r1)*(x1-x0),Math.PI*r1*r1,0,"ADIABATIC",Map.of(),List.of(),profile,null,null);}
}
